version: '3.8'
services:
    postgres:
        container_name: container-pg
        image: postgres
        hostname: localhost
        ports:
            - "5435:5432"
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: root
            POSTGRES_DB: my_app
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    postgres-data: